sudo: required

language: c

services:
    - docker

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libtalloc-dev libarchive-dev uthash-dev gdb strace realpath swig

script:
  - make -C src loader.exe loader-m32.exe build.h 
  - env CFLAGS=--coverage LDFLAGS='--coverage' make -C src proot care
  - env PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PWD/src PROOT_NO_SECCOMP=1 make -C tests

